version: 0.2

#@env:
#  variables:
#S3_BUCKET_NAME: "ci-cd-s3-codedeploy-bucket"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli

  pre_build:
    commands:
      - npm install
      - npm --version
      - node -v

  build:
    commands:
      - ng build
      - aws s3 sync build/ s3://ci-cd-s3-codedeploy-bucket

artifacts:
  files:
    - '**/*'

