version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g @angular/cli

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - ng build --prod

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/'
  name: 'angular-app'
  bucket-name: 'ci-cd-s3-codedeploy-bucket'

cache:
  paths:
    - node_modules/**
