version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli

  pre_build:
    commands:
      - npm install
      - npm --version
      - node -v

  build:
    commands:
      - ng build --prod

artifacts:
  files:
    - '**/*'
  base-directory: 'ci-cd-s3-codedeploy-bucket/dist/dist/'  # Assuming the build artifacts are in the dist/ directory
  name: 'angular-app'

cache:
  paths:
    - node_modules/**
